### ISSUE TITLE
cannot run

### ISSUE THREAD

**Issue by warlolz999** [vishalshirke7/Cab-Booking-System#1]
Hello. Somehow I could not run this project in my computer. 

I consistently receive this error

Traceback (most recent call last):
  File "./manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/zerox9/anaconda3/envs/django/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/zerox9/anaconda3/envs/django/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/zerox9/anaconda3/envs/django/lib/python3.7/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/zerox9/anaconda3/envs/django/lib/python3.7/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/home/zerox9/anaconda3/envs/django/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/zerox9/anaconda3/envs/django/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 82, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/home/zerox9/anaconda3/envs/django/lib/python3.7/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/zerox9/anaconda3/envs/django/lib/python3.7/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/home/zerox9/anaconda3/envs/django/lib/python3.7/site-packages/django/db/migrations/loader.py", line 273, in build_graph
    raise exc
  File "/home/zerox9/anaconda3/envs/django/lib/python3.7/site-packages/django/db/migrations/loader.py", line 247, in build_graph
    self.graph.validate_consistency()
  File "/home/zerox9/anaconda3/envs/django/lib/python3.7/site-packages/django/db/migrations/graph.py", line 243, in validate_consistency
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "/home/zerox9/anaconda3/envs/django/lib/python3.7/site-packages/django/db/migrations/graph.py", line 243, in <listcomp>
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "/home/zerox9/anaconda3/envs/django/lib/python3.7/site-packages/django/db/migrations/graph.py", line 96, in raise_error
    raise NodeNotFoundError(self.error_message, self.key, origin=self.origin)
django.db.migrations.exceptions.NodeNotFoundError: Migration driverAPI.0007_driverlocation_driverrideshistory dependencies reference nonexistent parent node ('passengerAPI', '0010_auto_20181023_1709')

**Comment by rachiitgupta** [comment]
experiencing the same error. Fix needed

**Comment by rachiitgupta** [comment]
I tried to clear up all the migrations in both the folders (driver & passengers). Just delete the migrations folder.
After this just run the command:
`python manage.py runserver`

**Comment by malaviyaprakash** [comment]
I also experiencing the same error but just change in the file.

first create virtual env. and follow this step to run this file.
1. open your virtual env.  in "lib" file open.
2. And open "site-packages" in "Lib".
3. And then open "rest_framework" in "site-packages".
4. And then open "utils" in "rest_framework".
5. And then open "serializer_helpers.py" in "utils".
6. Go to "**BindingDict**" Class in "serializer_helpers.py"
7. **And just change "collections.MutableMapping" to "collections.abc.MutableMapping".**
8. And run the main file python manage.py runserver.
9. Also delete the migrations files. and then migrate and run.
